### ISSUE TITLE
Speaking Code

### ISSUE THREAD

**Issue by Briebuzz** [Briebuzz/components-on-a-grid#1]
@thatkidmadrid
[buzzell-brianne-030-speaking-code.m4a.zip](https://github.com/Briebuzz/components-on-a-grid/files/7228537/buzzell-brianne-030-speaking-code.m4a.zip)

**Comment by thatkidmadrid** [comment]
Looks good and sounds good 👍 
Only weird thing I see is the negative margin in your figure; removing the padding from the figure would let you just set the margin to 0, and everything else would be good to go, but you got it to match the 1000px reference so 🙌
